### ISSUE TITLE
[GSOC 2021]: Requesting to work on Idea from Idealist

### ISSUE THREAD

**Issue by jugshaurya** [react-native-elements/.github#1]
Hello @dabit3 @pranshuchittora @flyingcircle, I would like to work on this [Idea 4](https://github.com/react-native-elements/org/blob/master/GSoC/ideas.md#4-embed-playground-in-the-document-website-medium) over my summer participating in GSOC 2021 with react-native-elements organization.  [Idea 2](https://github.com/react-native-elements/org/blob/master/GSoC/ideas.md#2-migration-to--hooks) also seems promising. 

But for now, I will be creating my proposal around [Idea 4](https://github.com/react-native-elements/org/blob/master/GSoC/ideas.md#4-embed-playground-in-the-document-website-medium).
 
May I continue? (Asking for permission).
- Also who is going to be the mentor for the same Idea?
- I am a Udacity Nanodegree graduated React Developer, looking forward to contributing to react-native-elements.
 ```
4. Embed Playground in the Document Website (Medium)
Difficulty: Medium | Tags: Website Merge

Currently, we have 2 websites for documentation.

Reactnativeelements.com This contains just the documentation of the components, build using docusaurus.
React-native-elements.js.org An interactive component playground.
The idea is to merge the two into one, i.e. the document website which embeds the Playground.
```

**Comment by jugshaurya** [comment]
Idea Solution: Adding a modal that will open after clicking on a button on the bottom right corner of the page(like that on [reactjs.org](reactjs.org) documentation page). This modal will have the functionality of the playground.

![Screenshot from 2021-03-12 13-23-08](https://user-images.githubusercontent.com/39825643/110911186-5d339180-8338-11eb-91e7-532d4502105d.png)

- Button will have `</> as a svg`
 

### More Thinking requirement from my side:
- [ ] how to fill modal with the playground website data.

### My progress
- [x] Successfully build Both Docs website after forking and cloning playground and react-native-elements repos

**Comment by pranshuchittora** [comment]
Pls use slack for such conversations.
Thanks
